// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTlpy3rH8n5B1qDozezclYA9aJQ_up6rI',
    appId: '1:713912149150:web:34caec381dc5eebf84878f',
    messagingSenderId: '713912149150',
    projectId: 'device-detect-b1e4a',
    authDomain: 'device-detect-b1e4a.firebaseapp.com',
    storageBucket: 'device-detect-b1e4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzxN15Qzgk5h7Mkd_v2H7KNUrZNlHgM7M',
    appId: '1:713912149150:android:02cfb38b87b8ff2c84878f',
    messagingSenderId: '713912149150',
    projectId: 'device-detect-b1e4a',
    storageBucket: 'device-detect-b1e4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhA00etfvXrc14IhMHFGUraiBcbl9wpu0',
    appId: '1:713912149150:ios:d148bb9d08e6645d84878f',
    messagingSenderId: '713912149150',
    projectId: 'device-detect-b1e4a',
    storageBucket: 'device-detect-b1e4a.appspot.com',
    iosBundleId: 'com.example.deviceInfoWeb',
  );
}
